import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/components/context/user-context";
import { verifyAuth } from "@/lib/auth";
import { getUserById } from "@/lib/users";
import { user as userType } from "@/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const { user } = await verifyAuth();
  let userData: userType | null = null;
  if (user) userData = getUserById(user.id) as userType;

  return (
    <html lang="en">
      <body>
        <UserProvider user={userData}>
          {modal}
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
