import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/components/context/user-context";
import { verifyAuth } from "@/lib/auth";
import { getUserById } from "@/lib/users";
import { Link, user as userType } from "@/types";
import { Toaster } from "@/components/ui/sonner";
import { getLinksByUser } from "@/lib/links";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const { user } = await verifyAuth();
  let userData: userType | null = null;
  if (user) userData = getUserById(user.id) as userType;

  let userLinks: Link[] | null = null;
  if (user) userLinks = getLinksByUser(user?.id).reverse() as Link[];

  return (
    <html lang="en">
      <body>
        <UserProvider user={userData} links={userLinks}>
          {modal}
          {children}
        </UserProvider>
        <Toaster
          theme="dark"
          toastOptions={{
            classNames: {
              toast: "bg-transparent shadow-none",
            },
          }}
        />
      </body>
    </html>
  );
}
